/**
 * Turning scored files into a verdict.
 *
 * Three independent things can fail a run, and each is reported separately
 * because they mean different things: a file that *errored* is a broken
 * harness or a broken input, a file over threshold is a conversion that is
 * wrong today, and a regression is a conversion that got worse than the
 * committed reference. A run that only checked the last of those - which this
 * one used to - passes green while every icon is visibly broken, as long as it
 * was equally broken last time.
 */
import fs from 'node:fs';
import path from 'node:path';

import { DEFAULT_THRESHOLDS, isFailing } from '../lib/thresholds';
import type { IconMetrics, Summary } from '../lib/thresholds';
import type { Config } from './config';
import type { ScoredFile } from './score';

export interface GateResult {
  /** Ids whose shape score is worse than the baseline by more than the slack. */
  regressions: string[];
  /**
   * Ids the baseline has never seen.
   *
   * There is nothing to compare these against, so they cannot be checked for a
   * regression - and that is exactly why they fail the run. Reporting them and
   * carrying on would let a whole new icon set land with silent exemption from
   * the suite, which is the one failure this harness exists to prevent.
   *
   * The fix is to look at the scores and run with `--update-baseline`.
   */
  unbaselined: string[];
  baselineWritten: 'created' | 'updated' | null;
  /**
   * Cases listed as expected failures that now pass.
   *
   * Good news, but still worth saying out loud: the limit moved, so the entry
   * should come out of the file. Reported, not fatal.
   */
  unexpectedPasses: string[];
  /** Non-empty means exit 1. One readable line per cause. */
  reasons: string[];
}

export function readBaseline(config: Config): Record<string, number> | null {
  return fs.existsSync(config.baselineFile)
    ? (JSON.parse(fs.readFileSync(config.baselineFile, 'utf-8')) as Record<string, number>)
    : null;
}

/**
 * Cases that are meant to fail, mapped to the reason.
 *
 * A few of the torture files cannot pass and should not. One is made entirely
 * of features the converter refuses to guess at. One measures the colour a
 * flattened gradient loses. Two are so small that the measurement itself
 * dominates the number. They hold documented limits in place: if this suite
 * ever reported zero failures, it would mean a threshold had been loosened or
 * the cases had been deleted.
 *
 * Keeping the list in a file rather than in the gate means it is reviewable in
 * a diff, and the website reads the same reasons rather than repeating them.
 */
export function readExpectedFailures(config: Config): Record<string, string> {
  return fs.existsSync(config.expectedFailuresFile)
    ? (JSON.parse(fs.readFileSync(config.expectedFailuresFile, 'utf-8')) as Record<string, string>)
    : {};
}

/**
 * The one thing a single icon cannot see: two icons minting the same `fileId`,
 * which would make the merged `files` map silently drop one of them.
 */
export function corpusIssues(scored: ScoredFile[]): string[] {
  const issues: string[] = [];
  const seen = new Set<string>();

  for (const file of scored) {
    for (const id of file.fileIds) {
      if (seen.has(id)) {
        issues.push(
          `package: fileId "${id}" is generated by more than one icon - the merged files map would drop one`
        );
      }
      seen.add(id);
    }
  }

  return issues;
}

export function summarise(metrics: IconMetrics[], extraIssues: string[]): Summary {
  const mean = (xs: number[]) => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : 0);
  const shapeScores = metrics.filter(m => m.shapeScore !== null).map(m => m.shapeScore as number);
  const placements = metrics
    .filter(m => m.placementErrorPx !== null)
    .map(m => m.placementErrorPx as number);

  return {
    generatedAt: new Date().toISOString(),
    totalProcessed: metrics.length,
    meanShapeScore: mean(shapeScores),
    worstShapeScore: shapeScores.length ? Math.max(...shapeScores) : 0,
    meanPlacementErrorPx: mean(placements),
    worstPlacementErrorPx: placements.length ? Math.max(...placements) : 0,
    failingIcons: metrics.filter(m => isFailing(m, DEFAULT_THRESHOLDS)).length,
    auditIssueCount: metrics.reduce((n, m) => n + m.auditIssues.length, 0) + extraIssues.length,
    thresholds: DEFAULT_THRESHOLDS,
    icons: metrics,
  };
}

export function applyGate(
  config: Config,
  summary: Summary,
  baseline: Record<string, number> | null,
  expectedFailures: Record<string, string> = {}
): GateResult {
  const scores: Record<string, number> = {};
  summary.icons.forEach(m => {
    if (m.shapeScore !== null) scores[m.id] = Number(m.shapeScore.toFixed(6));
  });

  const regressions: string[] = [];
  const unbaselined: string[] = [];
  let baselineWritten: GateResult['baselineWritten'] = null;



  // A `--only` run sees a subset of icons, so it must never be allowed to
  // read a partial verdict from - or write a partial reference to - the
  // full-corpus baseline.
  if (config.only) {
    // nothing read, nothing written
  } else if (config.updateBaseline) {
    fs.mkdirSync(path.dirname(config.baselineFile), { recursive: true });
    fs.writeFileSync(config.baselineFile, JSON.stringify(scores, null, 2), 'utf-8');
    baselineWritten = baseline ? 'updated' : 'created';
  } else {
    // A missing baseline file is NOT quietly written here. A suite that mints
    // its own reference on first run has never been reviewed by anyone, and it
    // would then pass forever at whatever quality it happened to launch with.
    for (const [id, score] of Object.entries(scores)) {
      const before = baseline?.[id];
      if (before === undefined) {
        unbaselined.push(id);
      } else if (score > before + summary.thresholds.regressionSlack) {
        regressions.push(`${id}: ${(before * 100).toFixed(2)}% -> ${(score * 100).toFixed(2)}%`);
      }
    }
  }

  const failing = summary.icons.filter(m => isFailing(m, summary.thresholds));

  // Over threshold and nobody has agreed to it. The regression check below
  // catches a listed case that gets *worse*, so an expected failure holding
  // steady is not a reason to fail the run.
  const unexpectedFailures = failing.filter(m => !(m.id in expectedFailures)).map(m => m.id);

  const unexpectedPasses = Object.keys(expectedFailures).filter(
    id => summary.icons.some(m => m.id === id) && !failing.some(m => m.id === id)
  );

  const errored = summary.icons.filter(m => m.error);
  const reasons: string[] = [];

  if (errored.length) {
    reasons.push(`${errored.length} file(s) errored during scoring`);
  }
  if (unexpectedFailures.length) {
    reasons.push(
      `${unexpectedFailures.length} file(s) over the thresholds ` +
        `(shape > ${(summary.thresholds.shapeScore * 100).toFixed(0)}%, ` +
        `placement > ${summary.thresholds.placementErrorPx}px, or any audit issue): ` +
        unexpectedFailures.join(', ')
    );
  }
  if (unbaselined.length) {
    reasons.push(
      `${unbaselined.length} file(s) have no baseline entry, so nothing is checking them. ` +
        `Review the scores above, then re-run with --update-baseline`
    );
  }
  if (regressions.length) {
    reasons.push(
      `${regressions.length} shape-score regression(s) vs ` +
        path.relative(process.cwd(), config.baselineFile)
    );
  }

  return { regressions, unbaselined, baselineWritten, unexpectedPasses, reasons };
}
